<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MongoChangeStream.DDD.Application\MongoChangeStream.DDD.Application.csproj" />
    <ProjectReference Include="..\MongoChangeStream.DDD.Infrastructure\MongoChangeStream.DDD.Infrastructure.csproj" />
  </ItemGroup>

</Project>
